import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import os

INPUT_CSV = 'shipment_audit_log.csv'
OUTPUT_HTML = 'Global_Supply_Chain_Dashboard.html'

def load_data():
    if not os.path.exists(INPUT_CSV):
        print("Audit Log not found.")
        return None
    df = pd.read_csv(INPUT_CSV)
    
    # Sort Months
    months_order = [
        "January", "February", "March", "April", "May", "June",
        "July", "August", "September", "October", "November", "December"
    ]
    df['Month'] = pd.Categorical(df['Month'], categories=months_order, ordered=True)
    df = df.sort_values(['Country', 'Month'])
    return df

def generate_dashboard():
    df = load_data()
    if df is None: return

    print("Generating Business Intelligence Dashboard...")

    # Aggregations
    df['Is_Rotten'] = df['Predicted_Status'] == 'Rotten'
    
    # 1. KPI: Global Spoilage Rate by Country
    country_perf = df.groupby('Country')['Is_Rotten'].mean().reset_index()
    fig1 = px.bar(country_perf, x='Country', y='Is_Rotten', 
                  title='1. Global Spoilage Rate by Country',
                  color='Is_Rotten', color_continuous_scale='RdYlGn_r',
                  labels={'Is_Rotten': 'Spoilage Rate'})

    # 2. Seasonality Trend (Line Chart)
    trend = df.groupby(['Month', 'Country'])['Is_Rotten'].mean().reset_index()
    fig2 = px.line(trend, x='Month', y='Is_Rotten', color='Country', markers=True,
                   title='2. Seasonal Spoilage Trends (Time Series)',
                   labels={'Is_Rotten': 'Spoilage Rate'})

    # 3. Fruit-Specific Heatmaps
    fruits = df['Fruit'].unique()
    fig3 = make_subplots(rows=1, cols=len(fruits), subplot_titles=[f"{f} Heatmap" for f in fruits])
    
    for i, fruit in enumerate(fruits):
        f_df = df[df['Fruit'] == fruit]
        pivot = f_df.groupby(['Country', 'Month'])['Is_Rotten'].mean().unstack()
        heatmap = go.Heatmap(z=pivot.values, x=pivot.columns, y=pivot.index, 
                             colorscale='RdYlGn_r', zmin=0, zmax=1, showscale=(i==len(fruits)-1))
        fig3.add_trace(heatmap, row=1, col=i+1)
    fig3.update_layout(title_text="3. Fruit-Specific Spoilage Heatmaps (Red = High Risk)")

    # 4. Volume Distribution
    vol = df.groupby(['Country', 'Predicted_Status']).size().reset_index(name='Count')
    fig4 = px.bar(vol, x='Country', y='Count', color='Predicted_Status', 
                  title='4. Shipment Volume & Quality Distribution',
                  color_discrete_map={'Fresh': 'green', 'Rotten': 'red'})

    # 5. Anomaly Detection (Scatter)
    # Highlight points with > 70% spoilage
    anomalies = trend[trend['Is_Rotten'] > 0.7]
    fig5 = px.scatter(trend, x='Month', y='Is_Rotten', color='Country', size='Is_Rotten',
                      title='5. Supply Chain Anomalies (Risk Detection)',
                      hover_data=['Country', 'Month'])
    if not anomalies.empty:
        fig5.add_annotation(x=anomalies.iloc[0]['Month'], y=anomalies.iloc[0]['Is_Rotten'],
                            text="Critical Failure Detected", showarrow=True, arrowhead=1)

    # 6. Confidence Distribution
    fig6 = px.histogram(df, x='Confidence', color='Predicted_Status', barmode='overlay',
                        title='6. AI Model Confidence Distribution',
                        color_discrete_map={'Fresh': 'green', 'Rotten': 'red'})

    # 7. Worst Performing Routes (Table)
    worst = trend.sort_values('Is_Rotten', ascending=False).head(5)
    worst['Is_Rotten'] = (worst['Is_Rotten'] * 100).round(1).astype(str) + '%'
    fig7 = go.Figure(data=[go.Table(
        header=dict(values=['Month', 'Country', 'Spoilage Rate'], fill_color='paleturquoise', align='left'),
        cells=dict(values=[worst.Month, worst.Country, worst.Is_Rotten], fill_color='lavender', align='left'))
    ])
    fig7.update_layout(title="7. Top 5 High-Risk Supply Routes")

    # Combine into HTML
    with open(OUTPUT_HTML, 'w') as f:
        f.write("<html><head><title>Global Supply Chain Intelligence</title></head><body>")
        f.write("<h1>🍎 Global Fruit Supply Chain Intelligence Dashboard</h1>")
        f.write("<h3>Generated by AI Data Mining Pipeline</h3>")
        f.write(fig1.to_html(full_html=False, include_plotlyjs='cdn'))
        f.write(fig2.to_html(full_html=False, include_plotlyjs='cdn'))
        f.write(fig3.to_html(full_html=False, include_plotlyjs='cdn'))
        f.write(fig4.to_html(full_html=False, include_plotlyjs='cdn'))
        f.write(fig5.to_html(full_html=False, include_plotlyjs='cdn'))
        f.write(fig6.to_html(full_html=False, include_plotlyjs='cdn'))
        f.write(fig7.to_html(full_html=False, include_plotlyjs='cdn'))
        f.write("</body></html>")

    print(f"Dashboard generated: {OUTPUT_HTML}")

if __name__ == "__main__":
    generate_dashboard()
